version: '3.8'

services:
    outboxworker:
        image: outboxworker
        build: 
            context: .
            dockerfile: OutboxWorker/Dockerfile
        ports: 
            - "8000:8000"
        depends_on:
            postgresCont:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
        restart: always
        networks:
            - PCRepairNetwork

    postgresCont:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: "12345678"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - PCRepairNetwork
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d PCRepairDB"]
            interval: 10s
            timeout: 5s
            retries: 3

    # adminer:
    #     image: adminer
    #     ports:
    #       - "9091:8080"
    #     environment:
    #       - ADMINER_PLUGINS=tinymce
    #       - ADMINER_DESIGN=flat
    #       - ADMINER_DEFAULT_SERVER=postgresCont
    #     networks:
    #       - PCRepairNetwork

    rabbitmq:
        image: rabbitmq:3.13-management
        ports:
          - "5672:5672"
          - "15672:15672"
        networks:
          - PCRepairNetwork
        healthcheck:
            test: ["CMD", "rabbitmqctl", "status"]
            interval: 30s
            timeout: 10s
            retries: 5
volumes: 
    postgres-data:
networks:
    PCRepairNetwork:
        driver: bridge

            
            